#pragma once
#include <vector>
#include "CTItem.h"

namespace CSC234 {
	class CTInventory {
	public:
		CTInventory();
		CTInventory(string, int);
		CTInventory(vector<CTItem*>);
		CTInventory(vector<CTItem*>, int);
		void setInventory(vector<CTItem*>);
		//void changeInventorySize(int);
		void addItem(CTItem*);
		void removeItem(int);
		CTItem* getItem(int);
		int findItem(CTItem*);
		void clearInventory();
		int getVectorSize();
		void printList();
		void printPersonalInventory();
		void printCampInventory();
		void printFoodInventory();
		vector<vector<CTItem*>> printStoreInventory();
		int size();
		void makeInventory(vector<CTItem*>, int);
		void makeInventory(vector<CTItem*>, vector<CTItem*>, int);
		void makeInventory(vector<CTItem*>, vector<CTItem*>, vector<CTItem*>, int);
		void makeInventory(vector<CTItem*>, vector<CTItem*>, vector<CTItem*>, vector<CTItem*>, int);
		void makeInventory(vector<CTItem*>, vector<CTItem*>, vector<CTItem*>, vector<CTItem*>, vector<CTItem*>, int);
		void makeInventory(vector<CTItem*>, vector<CTItem*>, vector<CTItem*>, vector<CTItem*>, vector<CTItem*>, vector<CTItem*>, int);
		vector<CTItem*> makeGeneralFoodInventory();
		vector<CTItem*> makeMedFoodInventory();
		vector<CTItem*> makeRareFoodInventory();
		vector<CTItem*> makeGeneralInventory();
		vector<CTItem*> makeMedInventory();
		vector<CTItem*> makeRareInventory();
		void makeRandomInventory(int);
		void setGeneralFoodInventory();
		void setMedFoodInventory();
		void setRareFoodInventory();
		void setGeneralInventory();
		void setMedInventory();
		void setRareInventory();
		void setGeneralFoodInventory(int);
		void setMedFoodInventory(int);
		void setRareFoodInventory(int);
		void setGeneralInventory(int);
		void setMedInventory(int);
		void setRareInventory(int);
		vector<CTItem*> getInventory();
		void printInventory();
		void printNumberedInventory();
		CTItem* emptyItem();
		CTItem* backgammon();
		CTItem* candles();
		CTItem* canvasyd();
		CTItem* cards();
		CTItem* letterpaper();
		CTItem* matches();
		CTItem* postage();
		CTItem* sewingkit();
		CTItem* shavehaircut();
		CTItem* soap();
		vector<CTItem*> generalGeneral = { candles(), matches() };
		vector<CTItem*> medGeneral = { canvasyd(), letterpaper(), postage(), sewingkit() };
		vector<CTItem*> rareGeneral = { backgammon(), cards(), soap() };
		CTHousehold* billy();
		CTHousehold* coffeepot();
		CTHousehold* drinkingglass();
		CTHousehold* ironpot();
		CTHousehold* knifefork();
		CTHousehold* teakettle();
		CTHousehold* tincup();
		vector<CTItem*> generalKitchen = { billy(), coffeepot(), drinkingglass(), ironpot(), knifefork() };
		vector<CTItem*> medKitchen = { teakettle() };
		CTHuntItems* gunpowderlb();
		CTHuntItems* leadlb();
		CTHuntItems* rifle();
		CTItem* nails();
		CTItem* pickaxe();
		CTItem* pocketknife();
		CTItem* screws();
		CTItem* shovel();
		vector<CTItem*> generalTools = { gunpowderlb(), leadlb(), nails(), pickaxe(), shovel() };
		vector<CTItem*> medTools = { pocketknife(), screws() };
		CTProtein* baconlb();
		CTProtein* baconlb(double);
		CTProtein* bacon100();
		CTProtein* bearmeat();
		CTProtein* bearmeat(double);
		CTProtein* beeflb();
		CTProtein* beeflb(double);
		CTProtein* canchicken();
		CTProtein* canoysters();
		CTProtein* cansalmon();
		CTProtein* duck();
		CTProtein* grouse();
		CTProtein* hams100();
		CTProtein* muttonlb();
		CTProtein* pheasant();
		CTProtein* salmon();
		CTProtein* sirloin();
		CTProtein* turkey();
		CTWildGame* noluck();
		CTWildGame* huntedantelope();
		CTWildGame* huntedantelope(double);
		CTWildGame* huntedbear();
		CTWildGame* huntedbear(double);
		CTWildGame* huntedbuffalo();
		CTWildGame* huntedbuffalo(double);
		CTWildGame* hunteddeer(); 
		CTWildGame* hunteddeer(double);
		CTWildGame* huntedduck();
		CTWildGame* huntedducks(double);
		CTWildGame* huntedelk();
		CTWildGame* huntedelk(double);
		CTWildGame* huntedgeese();
		CTWildGame* huntedgeese(double);
		CTWildGame* huntedgrouse();
		CTWildGame* huntedgrouses(double);
		CTWildGame* pinenuts();
		CTWildGame* pinenuts(double);
		CTWildGame* huntedpheasant();
		CTWildGame* huntedpheasants(double);
		CTWildGame* wildraspberries();
		CTWildGame* wildraspberries(double);
		CTWildGame* huntedrabbit();
		CTWildGame* huntedrabbits(double);
		CTWildGame* caughttrout();
		CTWildGame* caughttrout(double);
		CTWildGame* huntedsquirrel();
		CTWildGame* huntedsquirrels(double);
		CTWildGame* wildstrawberries();
		CTWildGame* wildstrawberries(double);
		CTWildGame* huntedturkey();
		CTWildGame* huntedturkeys(double);

		vector<CTItem*> generalMeat = { baconlb(), bacon100(), beeflb(), hams100() };
		vector<CTItem*> medMeat = { duck(), grouse(), muttonlb(), pheasant(), sirloin(), turkey() };
		vector<CTItem*> rareMeat = { bearmeat(), canchicken(), cansalmon(), canoysters(), salmon() };
		CTItem* beer();
		CTItem* tobacco();
		CTItem* whiskey();
		vector<CTItem*> indulgences = { beer(), tobacco(), whiskey() };
		CTFood* butter();
		CTFood* cheese();
		CTFood* condmilk();
		CTFood* milk();
		vector<CTItem*> medDairy = { butter() };
		vector<CTItem*> rareDairy = { cheese(), condmilk(), milk() };
		CTFruitVeg* canfruit();
		CTFruitVeg* currants();
		CTFruitVeg* driedappleslb();
		CTFruitVeg* peaches();
		CTFruitVeg* raisins();
		vector<CTItem*> generalFruit = { driedappleslb() };
		vector<CTItem*> medFruit = { raisins() };
		vector<CTItem*> rareFruit = { canfruit(), currants(), peaches() };
		CTFood* chocolate();
		CTFood* fruitpie();
		CTFood* jamstraw();
		CTFood* molasses();
		CTFood* sugarlb();
		CTFood* sugar100();
		vector<CTItem*> generalSweets = { sugar100() };
		vector<CTItem*> medSweets = { molasses(), sugarlb() };
		vector<CTItem*> rareSweets = { chocolate(), fruitpie(), jamstraw() };
		CTFood* coffee();
		CTFood* lardlb();
		CTFood* oilgal();
		CTFood* saltlb();
		CTFood* spices();
		CTFood* tea();
		vector<CTItem*> generalMisc = { coffee(), lardlb() };
		vector<CTItem*> medMisc = { oilgal(), saltlb() };
		vector<CTItem*> rareMisc = { spices(), tea() };
		CTCarb* beanslb();
		CTCarb* cake();
		CTCarb* cornmeallb();
		CTCarb* crackers();
		CTCarb* flourlb();
		CTCarb* flour100();
		CTCarb* loafofbread();
		CTCarb* oatslb();
		CTCarb* ricelb();
		CTCarb* rice100();
		vector<CTItem*> generalStarches = { beanslb(), flour100(), rice100() };
		vector<CTItem*> medStarches = { cornmeallb(), oatslb(), flourlb()};
		vector<CTItem*> rareStarches = { cake(), crackers(), loafofbread(), ricelb() };
		CTFruitVeg* canveg();
		CTFruitVeg* cornlb();
		CTFruitVeg* cornbushel();
		CTFruitVeg* driedcorn();
		CTCarb* potatoeslb();
		vector<CTItem*> generalVeg = { cornlb(), cornbushel() };
		vector<CTItem*> medVeg = { potatoeslb() };
		vector<CTItem*> rareVeg = { canveg(), driedcorn() };
		CTHousehold* bedblanketwool();
		CTHousehold* bedcomforterwool();
		CTHousehold* bedcovercanvas();
		CTHousehold* bedquilt();
		CTHousehold* linensheets();
		CTHousehold* pillowfeather();
		CTHousehold* towel();
		vector<CTItem*> allLinens = { bedblanketwool(), bedcomforterwool(), bedcovercanvas(), bedquilt(), linensheets(), pillowfeather(), towel() };
		vector<CTItem*> generalLinens = { bedblanketwool(), bedcovercanvas() };
		vector<CTItem*> medLinens = { bedcomforterwool(), bedquilt(), linensheets() };
		vector<CTItem*> rareLinens = { pillowfeather(), towel() };
		CTHousehold* heater();
		CTHousehold* stovemedium();
		CTHousehold* stovelarge();
		CTHousehold* washbasin();
		vector<CTItem*> heatStove = { heater(), stovemedium(), stovelarge() };
		CTClothes* emptyClothes();
		CTClothes* bootsdressleather();
		CTClothes* bootsrubber();
		CTClothes* bootsworkleather();
		CTClothes* coatjacket();
		CTClothes* coatwaist();
		CTClothes* coatwoolover();
		CTClothes* coverallsdenim();
		CTClothes* glovesleather();
		CTClothes* hatfelt();
		CTClothes* leatherbelt();
		CTClothes* mittenswool();
		CTClothes* necktie();
		CTClothes* pantsdresscotton();
		CTClothes* pantsworkblack();
		CTClothes* pantsworkdenim();
		CTClothes* pantsworkheavy();
		CTClothes* pantsworkwool();
		CTClothes* shirtdresscotton();
		CTClothes* shirtworkblack();
		CTClothes* shirtworkcotton();
		CTClothes* shirtworkplaid();
		CTClothes* shoesdress();
		CTClothes* socksheavywool();
		CTClothes* sockswool();
		CTClothes* vestwool();
		CTClothes* undergarments();
		vector<CTItem*> generalClothes = { bootsworkleather(), coatjacket(), hatfelt(), necktie(), pantsworkdenim(), shirtworkcotton(), sockswool() };
		vector<CTItem*> medClothes = { bootsrubber(), coatwaist(), pantsworkwool(), shirtworkplaid(), vestwool() };
		vector<CTItem*> rareClothes = { coatwoolover(), coverallsdenim(), glovesleather(), mittenswool(), pantsworkblack(), pantsworkheavy(), shirtworkblack(), socksheavywool(), undergarments(), bootsdressleather(), pantsdresscotton(), shirtdresscotton() };
		vector<CTItem*> summerClothes = { pantsdresscotton(), pantsworkdenim(), shirtworkcotton() };
		vector<CTItem*> winterClothes = { coatjacket(), coatwoolover(), mittenswool(), pantsworkwool(), socksheavywool(), vestwool(), undergarments() };
		vector<CTItem*> cabinItems = { bedblanketwool(), bedcomforterwool(), bedcovercanvas(), bedquilt(), heater(), linensheets(), pillowfeather(), stovemedium(), stovelarge(), towel(), washbasin() };
	private:
		vector<CTItem*> inventory;
		vector<CTItem*> tempInventory;
		double noexpiration = 999.9;
		int vectorSize;
		void setVectorSize(int);
	};
}
